### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [OpenMD/OpenMD#12]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [RestraintForceManager](https://github.com/OpenMD/OpenMD/blob/7c5789b79291119510bb457f6c33631b7c7ca993/src/restraints/RestraintForceManager.cpp#L310 "Destructor for RestraintForceManager")
- [ZconstraintForceManager](https://github.com/OpenMD/OpenMD/blob/7c5789b79291119510bb457f6c33631b7c7ca993/src/constraints/ZconstraintForceManager.cpp#L184 "Destructor for ZconstraintForceManager")
- [ZConsVisitor](https://github.com/OpenMD/OpenMD/blob/7c5789b79291119510bb457f6c33631b7c7ca993/src/visitors/ZconsVisitor.cpp#L112 "Destructor for ZConsVisitor")

**Comment by gezelter** [comment]
Sounds reasonable.  Closed via 25584224ae11e227b0c89df2d45d5e596c4f012f

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/OpenMD/OpenMD/commit/25584224ae11e227b0c89df2d45d5e596c4f012f "Removing extra null pointer checks").
