### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [OpenMD/OpenMD#13]
Would you like to [wrap any pointer data members](https://github.com/OpenMD/OpenMD/blob/4ec41489c497fc797bed0115e8c33d0427efb9ab/src/nonbonded/InteractionManager.cpp#L52 "Update candidate: InteractionManager class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by elfring** [comment]
I suggest to [achieve safe resource management](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”").

**Comment by crdrisko** [comment]
`std::unique_ptr<>` won't work for these data members as multiple pointers exist at the same time to the same resource. A `std::shared_ptr<>` may work in this instance but may cause issues with the interface. If it's possible it will be addressed when issue #18 is addressed.
