### ISSUE TITLE
atom2omd bungles up pdb files with multiple chains

### ISSUE THREAD

**Issue by MeeMaster** [OpenMD/OpenMD#15]
Some residues get atom indices from residues from the other chain of the molecule.
e.g.:

[ABA_01.zip](https://github.com/OpenMD/OpenMD/files/3863799/ABA_01.zip)

**Comment by gezelter** [comment]
atom2omd uses openbabel to parse pdb files, and it looks like the residue names are coming back from the other chain via openbabel. We'll look into this.

**Comment by crdrisko** [comment]
This seems to be an issue on [openbabel](https://github.com/openbabel/openbabel)'s end. We've tested just `openbabel` on the same file and always get the "1 molecule converted" message.
