### ISSUE TITLE
Expand the docs

### ISSUE THREAD

**Issue by MeeMaster** [OpenMD/OpenMD#16]
I started using openMD and I have no idea how to apply restraints;
Even though I defined a "Restraint_file" parameter, I get an error:
`RestReader: Cannot open file: idealCrystal.in`

There is no instruction on how to build a restraint file

**Comment by gezelter** [comment]
Restraint files are just standard OpenMD dump files, but with the reference structure stored in the first frame (frame 0).  This file needs to match exactly the topology set up for your simulation.  If you want to submit a copy of your simulation setup we can try to diagnose why your "Restraint_file" parameter is not being parsed.  Check that this parameter is defined outside of any restraint block that you have set up.

We'll try to address this in the next version of the docs.

**Comment by crdrisko** [comment]
[This](https://github.com/OpenMD/OpenMD-docs/commit/a2093051f36f5c8d02755edbc28f45d4ac20cf69) commit to the OpenMD-docs addresses this issue in chapter 7, page 79.
