### ISSUE TITLE
Running OpenMD on multiple processors

### ISSUE THREAD

**Issue by MeeMaster** [OpenMD/OpenMD#21]
How can I run my simulation using multiple processors?
If i run:
`mpirun -np8 openmd warm.omd`
It just starts 8 simultaneous simulations of the same object.
Running:
`openmd_MPI warm.omd`
runs a single process.

**Comment by gezelter** [comment]
Just combine those two lines:

`mpirun -np 8 openmd_MPI warm.omd`

The openmd_MPI program has the built-in MPI calls.
